name: alphagrit
description: AlphaGrit – brutalist fitness & community app (Flutter)
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  dio: ^5.7.0
  supabase_flutter: ^2.6.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  sentry_flutter: ^8.6.0
  shared_preferences: ^2.3.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/textures/
    - assets/images/
